// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"time"
)

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (token, email, expires_at) VALUES (?, ?, ?)
`

type CreateMagicLinkParams struct {
	Token     string
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, createMagicLink, arg.Token, arg.Email, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getMagicLink = `-- name: GetMagicLink :one
SELECT token, email, expires_at, used_at FROM magic_links WHERE token = ? AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetMagicLink(ctx context.Context, token string) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, getMagicLink, token)
	var i MagicLink
	err := row.Scan(
		&i.Token,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at, created_at FROM sessions WHERE token = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE magic_links SET used_at = CURRENT_TIMESTAMP WHERE token = ?
`

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markMagicLinkUsed, token)
	return err
}
