// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (invite_code, title, organizer_id, status) VALUES (?, ?, ?, 'open') RETURNING id, invite_code, title, organizer_id, status, created_at, drawn_at
`

type CreateGroupParams struct {
	InviteCode  string
	Title       string
	OrganizerID int64
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.InviteCode, arg.Title, arg.OrganizerID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.Title,
		&i.OrganizerID,
		&i.Status,
		&i.CreatedAt,
		&i.DrawnAt,
	)
	return i, err
}

const drawGroup = `-- name: DrawGroup :execresult
UPDATE groups SET status = 'drawn', drawn_at = CURRENT_TIMESTAMP WHERE id = ? AND status = 'open'
`

func (q *Queries) DrawGroup(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, drawGroup, id)
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, invite_code, title, organizer_id, status, created_at, drawn_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.Title,
		&i.OrganizerID,
		&i.Status,
		&i.CreatedAt,
		&i.DrawnAt,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, invite_code, title, organizer_id, status, created_at, drawn_at FROM groups WHERE invite_code = ?
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.Title,
		&i.OrganizerID,
		&i.Status,
		&i.CreatedAt,
		&i.DrawnAt,
	)
	return i, err
}
