// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countMembersByGroup = `-- name: CountMembersByGroup :one
SELECT COUNT(*) FROM memberships WHERE group_id = ?
`

func (q *Queries) CountMembersByGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembersByGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (group_id, user_id, wishlist) VALUES (?, ?, ?) RETURNING id, group_id, user_id, wishlist, recipient_id, created_at
`

type CreateMembershipParams struct {
	GroupID  int64
	UserID   int64
	Wishlist string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, createMembership, arg.GroupID, arg.UserID, arg.Wishlist)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Wishlist,
		&i.RecipientID,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, group_id, user_id, wishlist, recipient_id, created_at FROM memberships WHERE id = ?
`

func (q *Queries) GetMembership(ctx context.Context, id int64) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Wishlist,
		&i.RecipientID,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByGroupAndUser = `-- name: GetMembershipByGroupAndUser :one
SELECT id, group_id, user_id, wishlist, recipient_id, created_at FROM memberships WHERE group_id = ? AND user_id = ?
`

type GetMembershipByGroupAndUserParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) GetMembershipByGroupAndUser(ctx context.Context, arg GetMembershipByGroupAndUserParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByGroupAndUser, arg.GroupID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Wishlist,
		&i.RecipientID,
		&i.CreatedAt,
	)
	return i, err
}

const getMyRecipient = `-- name: GetMyRecipient :one
SELECT u.name, m.wishlist
FROM memberships m
JOIN users u ON u.id = m.recipient_id
WHERE m.group_id = ? AND m.user_id = ? AND m.recipient_id IS NOT NULL
`

type GetMyRecipientParams struct {
	GroupID int64
	UserID  int64
}

type GetMyRecipientRow struct {
	Name     string
	Wishlist string
}

func (q *Queries) GetMyRecipient(ctx context.Context, arg GetMyRecipientParams) (GetMyRecipientRow, error) {
	row := q.db.QueryRowContext(ctx, getMyRecipient, arg.GroupID, arg.UserID)
	var i GetMyRecipientRow
	err := row.Scan(&i.Name, &i.Wishlist)
	return i, err
}

const listMembershipsByGroup = `-- name: ListMembershipsByGroup :many
SELECT id, group_id, user_id, wishlist, recipient_id, created_at FROM memberships WHERE group_id = ?
`

func (q *Queries) ListMembershipsByGroup(ctx context.Context, groupID int64) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Wishlist,
			&i.RecipientID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecipient = `-- name: SetRecipient :exec
UPDATE memberships SET recipient_id = ? WHERE group_id = ? AND user_id = ?
`

type SetRecipientParams struct {
	RecipientID sql.NullInt64
	GroupID     int64
	UserID      int64
}

func (q *Queries) SetRecipient(ctx context.Context, arg SetRecipientParams) error {
	_, err := q.db.ExecContext(ctx, setRecipient, arg.RecipientID, arg.GroupID, arg.UserID)
	return err
}

const updateWishlist = `-- name: UpdateWishlist :exec
UPDATE memberships SET wishlist = ? WHERE id = ?
`

type UpdateWishlistParams struct {
	Wishlist string
	ID       int64
}

func (q *Queries) UpdateWishlist(ctx context.Context, arg UpdateWishlistParams) error {
	_, err := q.db.ExecContext(ctx, updateWishlist, arg.Wishlist, arg.ID)
	return err
}
