// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (group_id, sender_id, recipient_id, direction, body) VALUES (?, ?, ?, ?, ?) RETURNING id, group_id, sender_id, recipient_id, direction, body, created_at
`

type CreateMessageParams struct {
	GroupID     int64
	SenderID    int64
	RecipientID int64
	Direction   string
	Body        string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.GroupID,
		arg.SenderID,
		arg.RecipientID,
		arg.Direction,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.RecipientID,
		&i.Direction,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, group_id, sender_id, recipient_id, direction, body, created_at FROM messages
WHERE group_id = ? AND sender_id = ? AND recipient_id = ? AND direction = ?
ORDER BY created_at DESC
LIMIT 50
`

type ListMessagesParams struct {
	GroupID     int64
	SenderID    int64
	RecipientID int64
	Direction   string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.GroupID,
		arg.SenderID,
		arg.RecipientID,
		arg.Direction,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.RecipientID,
			&i.Direction,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, group_id, sender_id, recipient_id, direction, body, created_at FROM messages
WHERE group_id = ? AND sender_id = ? AND recipient_id = ? AND direction = ? AND id < ?
ORDER BY created_at DESC
LIMIT 50
`

type ListMessagesBeforeParams struct {
	GroupID     int64
	SenderID    int64
	RecipientID int64
	Direction   string
	ID          int64
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBefore,
		arg.GroupID,
		arg.SenderID,
		arg.RecipientID,
		arg.Direction,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.RecipientID,
			&i.Direction,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
