// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Group struct {
	ID          int64
	InviteCode  string
	Title       string
	OrganizerID int64
	Status      string
	CreatedAt   time.Time
	DrawnAt     sql.NullTime
}

type MagicLink struct {
	Token     string
	Email     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
}

type Membership struct {
	ID          int64
	GroupID     int64
	UserID      int64
	Wishlist    string
	RecipientID sql.NullInt64
	CreatedAt   time.Time
}

type Message struct {
	ID          int64
	GroupID     int64
	SenderID    int64
	RecipientID int64
	Direction   string
	Body        string
	CreatedAt   time.Time
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Email     string
	Name      string
	CreatedAt time.Time
}
